eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
# explicit enable hystrix feature, which is default disabled.
feign:
 hystrix:
  enabled: true